__version__ = "0.1.0"
__author__ = "Samphan Pojanasophanakul"
__copyright__ = "Copyright 2020 apptiviz.com"
__maintainer__ = "Samphan Pojanasophanakul"
__email__ = "nhapentor@gmail.com"
__license__ = "MIT"